// A curated list of top tech companies with significant India presence.
// This is a starter list and can be expanded easily.
export const INDIA_TECH_COMPANIES: string[] = [
  'TCS',
  'Infosys',
  'Wipro',
  'HCLTech',
  'Tech Mahindra',
  'LTIMindtree',
  'Persistent Systems',
  'Mphasis',
  'Cognizant',
  'Accenture',
  'Capgemini',
  'IBM',
  'Oracle',
  'Google',
  'Microsoft',
  'Amazon',
  'Apple',
  'Meta',
  'Salesforce',
  'Adobe',
  'SAP',
  'ServiceNow',
  'VMware',
  'NVIDIA',
  'Intel',
  'AMD',
  'Qualcomm',
  'Cisco',
  'Uber',
  'Lyft',
  'Airbnb',
  'Stripe',
  'PayPal',
  'Intuit',
  'Netflix',
  'Spotify',
  'Twilio',
  'Atlassian',
  'LinkedIn',
  'DoorDash',
  'Snowflake',
  'Databricks',
  'MongoDB',
  'Confluent',
  'HashiCorp',
  'Cloudflare',
  'DigitalOcean',
  'Dropbox',
  'Zoom',
  'Slack',
  'Zomato',
  'Swiggy',
  'Flipkart',
  'Myntra',
  'PhonePe',
  'Paytm',
  'Razorpay',
  'CRED',
  'Meesho',
  'Ola',
  'Rapido',
  'Freshworks',
  'Zoho',
  'InMobi',
  'BYJU’S',
  'Unacademy',
  'upGrad',
  'ShareChat',
  'Dream11',
  'Polygon Labs',
  'Rupeek',
  'Groww',
  'Zerodha',
  'Smallcase',
  'BridgeLabz',
  'Tata Digital',
  'Reliance Jio',
  'Airtel',
  'Nykaa',
  'CureFit',
  'Udaan',
  'Rivigo',
  'Delhivery',
  'RazorpayX',
  'Postman',
  'Chargebee',
  'CoinSwitch',
  'CoinDCX',
  'BrowserStack',
  'ClearTax',
  'Urban Company',
  'MakeMyTrip',
  'OYO',
  'Freshdesk',
  'Sprinklr',
  'Mu Sigma',
  'Fractal Analytics'
];


